[package]
name = "leaf-demo-1"
version = "0.1.1"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
collenchyma = { version = "*", default-features = false, features = [ "native", "cuda" ]}